version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=payment
      - MYSQL_USER=client 
      - MYSQL_PASSWORD=client