version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - DATABASE=payment
      - DB_USER=client 
      - DB_PASSWORD=client
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=payment
      - MYSQL_USER=client 
      - MYSQL_PASSWORD=client
      - MYSQL_ROOT_PASSWORD=root